# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: h2lab/runner-azure:latest

jobs:
- job: disco_blinky
  steps:
  - script: |
      source /etc/bash.bashrc
      mkdir build
      cd build
      repo init -u https://github.com/wookey-project/manifest.git -m soft/disco407_nightly.xml
      repo sync
      echo 'ADA_RUNTIME=/opt/adacore-arm-eabi' > setenv.local.sh
      echo 'JAVA_SC_SDK=/opt/oracle_sdks/jc303_kit' >> setenv.local.sh
      echo 'CROSS_COMPILE=arm-none-eabi-' >> setenv.local.sh
      source setenv.sh
      make 32f407discovery/proj_demo/basic_blinky_defconfig
      make
- job: disco_blinky_ipc
  steps:
  - script: |
      source /etc/bash.bashrc
      mkdir build
      cd build
      repo init -u https://github.com/wookey-project/manifest.git -m soft/disco407_nightly.xml
      repo sync
      echo 'ADA_RUNTIME=/opt/adacore-arm-eabi' > setenv.local.sh
      echo 'JAVA_SC_SDK=/opt/oracle_sdks/jc303_kit' >> setenv.local.sh
      echo 'CROSS_COMPILE=arm-none-eabi-' >> setenv.local.sh
      source setenv.sh
      make 32f407discovery/proj_demo/blinky_ipc_defconfig
      make
- job: disco_logger
  steps:
  - script: |
      source /etc/bash.bashrc
      mkdir build
      cd build
      repo init -u https://github.com/wookey-project/manifest.git -m soft/disco407_nightly.xml
      repo sync
      echo 'ADA_RUNTIME=/opt/adacore-arm-eabi' > setenv.local.sh
      echo 'JAVA_SC_SDK=/opt/oracle_sdks/jc303_kit' >> setenv.local.sh
      echo 'CROSS_COMPILE=arm-none-eabi-' >> setenv.local.sh
      source setenv.sh
      make 32f407discovery/proj_demo/logger_defconfig
      make
- job: disco_syscalls
  steps:
  - script: |
      source /etc/bash.bashrc
      mkdir build
      cd build
      repo init -u https://github.com/wookey-project/manifest.git -m soft/disco407_nightly.xml
      repo sync
      echo 'ADA_RUNTIME=/opt/adacore-arm-eabi' > setenv.local.sh
      echo 'JAVA_SC_SDK=/opt/oracle_sdks/jc303_kit' >> setenv.local.sh
      echo 'CROSS_COMPILE=arm-none-eabi-' >> setenv.local.sh
      source setenv.sh
      make 32f407discovery/proj_demo/syscalls_testsuite_defconfig
      make
- job: wookey_graphic
  steps:
  - script: |
      source /etc/bash.bashrc
      mkdir build
      cd build
      repo init -u https://github.com/wookey-project/manifest.git -m soft/disco407_nightly.xml
      repo sync
      echo 'ADA_RUNTIME=/opt/adacore-arm-eabi' > setenv.local.sh
      echo 'JAVA_SC_SDK=/opt/oracle_sdks/jc303_kit' >> setenv.local.sh
      echo 'CROSS_COMPILE=arm-none-eabi-' >> setenv.local.sh
      source setenv.sh
      make wookey/proj_wookey/wookey-v2/graphic_hs_defconfig
      make

stages:
- stage: compile_disco
  jobs:
    - job: disco_blinky
    - job: disco_blinky_ipc
    - job: disco_logger
    - job: disco_syscalls
- stage: compile_wookey
  jobs:
    - job: wookey_graphic

