# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: h2lab/runner-azure:latest

steps:
- script: |
    mkdir build
    cd build
    repo init -u https://github.com/wookey-project/manifest.git -m soft/wookey-nightly.xml
    repo sync
    echo 'ADA_RUNTIME=/opt/adacore-arm-eabi' > setenv.local.sh
    echo 'JAVA_SC_SDK=/opt/oracle_sdks/jc303_kit' >> setenv.local.sh
    echo 'CROSS_COMPILE=arm-none-eabi-' >> setenv.local.sh
    source /build/.bashrc
    source setenv.sh
    make wookey/proj_wookey/wookey-v2/graphic_hs_defconfig
  displayName: 'periodic nightly test'
